- Cargo.toml
- src/lib.rs
This PR adds a branch and bound `utxo` selection.  Currently all structs are self-contained, however, it might be worthwhile to use external structs in the future.
> Add coin selection

- src/lib.rs
Fixes the compile error when running `cargo doc --open`.
> Use automatic links

- src/lib.rs
Update the documentation header to match other rust bitcoin projects.  For example: https://docs.rs/bitcoin_hashes/0.11.0/bitcoin_hashes/
> Update the rustdocs header

- src/lib.rs
To keep pace with changes in Bitcoin Core, this PR removes the condition that returns early if a result with a waste of zero is found.  The matching Bitcoin Core PR is [here](https://github.com/bitcoin/bitcoin/pull/25495).
The other reason why I want to implement this change is so that we can get an accurate benchmark comparison between this implementation and Bitcoin Core.  This change essentially makes every search an exhaustive search of the search space since there is no known optimal solution to halt on.
> Do not return when waste is zero because waste could be negative

- src/branch_and_bound.rs
- src/lib.rs
Small refactor to the test module that adds `assert_coin_select`.  Use new helper method in select_coins_tests 1-10.
> refactor: Add assert_coin_select to test module

- src/lib.rs
This trait is no longer being used.
> Remove unused trait

- Cargo.toml
- README.md
- fuzz/Cargo.toml
- run_proptests.sh
- src/branch_and_bound.rs
- src/lib.rs
- src/single_random_draw.rs
Adds proptests using arbtest to test the correctness of the solutions provided by the SRD and BnB search algos.  I use the dep exhaustigen to build all possible solutions and then run SRD or BnB and compare the results to show that the correct solution is found.  Also, BnB contains a few proptest where a UTXO pool is randonly generated, and either one or many of the UTXOs are selected as a target with the assertion that BnB will find those UTXOS as the solution while searching.
> Add arbtest

- fuzz/Cargo.toml
Fuzzing is currently broken as documented because the dependency commit hash is out of sync.
> Update dependency commit hash

- README.md
Update docs to make them less terrible:
* Add install instruction for cargo fuzz to README
* Improve header titles
* stylize terminal commands
* fill out description section for property tests and fuzz tests
> Add install instructions for cargo fuzz

- src/branch_and_bound.rs
- src/lib.rs
- src/single_random_draw.rs
* Implements  FromStr for Utxo.
* Replace helper methods with FromStr trait
* Refactor Utxo using the builder pattern.
* Add constructors to UtxoPool
> Add utxo to string from string

- benches/coin_selection.rs
- src/branch_and_bound.rs
- src/lib.rs
- src/single_random_draw.rs
When refactoring or applying changes, testing the iteration count helps to catch inadvertent changes to the core algorithm competency.  Also, coin-grinder implements an iteration count, so this helps to unify the interface between the various selection algorithms.
A side note on this implementation is that if the algorithm returns None for results, then no iteration count is returned.  I'd like to
change this however it would make sense to change this when I remove the None type return and replace it with more verbose error messaging.  For now, in all tests that expect a None return, the test asserts the iteration count is zero.
> Add iteration count

- README.md
- src/branch_and_bound.rs
- src/lib.rs
- src/single_random_draw.rs
If the index_selection is not empty, and if the previous UTXO was excluded, then check the effective_value of the current UTXO.  If it has the same effective_value then skip searching this branch.
> Apply previous UTXO shortcut optimization

- benches/coin_selection.rs
- src/branch_and_bound.rs
- src/lib.rs
- src/single_random_draw.rs
An earlier implementation called collect() before returning the results. Instead of calling collect(), the API was changed to just return the iterator since it's possible dependant applications may prefer to use the iterator.  However, after a refactor, the call to collect() was removed, and now it no longer makes sense to return an iterator. Furthermore, return an opaque type makes for a more complicated return type, making it hard to alias for example.  Returning a concrete type therefore simplifies the API.
> Return vector instead of iterator

- src/branch_and_bound.rs
- src/single_random_draw.rs
If the test framework asserts that a result can be found, and yet there isn't a result found, the tests should panic.  This subtle bug in the test framework was introduced in a recent commit:
https://github.com/yancyribbens/rust-bitcoin-coin-selection/commit/780d14e95c55cf785093107480e94e2f8adcc471
> bug: test: Add panic when no results found

- src/branch_and_bound.rs
- src/single_random_draw.rs
`assert_coin_select()` uses default settings minimizing the number of arguments needed.  `assert_coin_select_params()` takes a struct of parameters which is more customizable.  However, both asserts are independently calling the search function, building a utxo pool, parsing arguments and asserting results.  By calling the more robust `assert_coin_select_params()` from within `assert_coin_select()`, the line count is reduced by consolidating duplicate functionality.
Remove the `FEE_RATE` const since now the fee_rate for the test is used in one place when creating the params to be passed to `asswert_coin_select_params()`.
Remove `build_pool()` for the same reason as removing `FEE_RATE` const since this is defined in the params now.
> refactor: Call helper function

- src/branch_and_bound.rs
- src/lib.rs
- src/single_random_draw.rs
Currently all tests are sat/kwu implicitly.  However, some tests that are copied from core use sat/vB and it would be nice to just copy the tests without doing a math conversion.  Add the ability to annotate the fee_rate as either sat/kwu or sat/vb.
> tests: Annotate fee_rate metric

- src/branch_and_bound.rs
- src/lib.rs
- src/single_random_draw.rs
A set of UTXOs for testing can be defined by either effective_value using `e()` or absolute value as default.
For example:
```rust
weighted_utxos: &["1 sat/68vb", "e(1 sat)/68 vb", "e(1 sat)/204 wu"]
```
This will evaluate to two `UTXOs` with equivalent effective_values of 1 sat even though they have different sizes (`68 vb` and `204 wu`).  Also, there will be a `UTXO` with negative effective value since the absolute value is given as `1 sat/68 vb` given some positive `fee_rate`.
Then, assert the smallest UTXO with a positive effective_value is returned:
```rust
expected_utxos: &["e(1 sat)/204 wu"]
```
Motivation:
During the selection process, input values are converted to effective_values, and then the search begins using the calculated effective_values.  In the test-suit, it's often the …
> test: Add ability to choose and assert by effective_value

- src/branch_and_bound.rs
- src/lib.rs
- src/single_random_draw.rs
"b" is the symbol for bit, and "B" is the symbol for byte, so a virtualbyte should have a capital B..
_Originally posted by @murchandamus in https://github.com/p2pderivatives/rust-bitcoin-coin-selection/pull/90#discussion_r2039804455_
> test: Reword vb to vB

- src/branch_and_bound.rs
The test might fail to find in-efficiency in the algorithms waste score calculation.  That is, the result could have a higher weight than the target_selection weight and there would be no failure in the test.  This was noticed when the following commit
118b1c419391943e0d80d6973fad3c07bd2ed918 was added but never triggered a fail in the test framework.  The commit adds an assertion such that if a result is found, the found result has a weight that is as good as the known solution or better.
> test: Add best weight assertion

- benches/coin_selection.rs
- fuzz/fuzz_targets/select_coins.rs
- fuzz/fuzz_targets/select_coins_bnb.rs
- fuzz/fuzz_targets/select_coins_srd.rs
- src/branch_and_bound.rs
- src/lib.rs
- src/single_random_draw.rs
Core uses just weight in coin-grinder, and it's complicated to maintain both satisfaction_weight and weight.  Therefore, switch to just weight units for all algorithms.
> Switch to weight

- README.md
- src/branch_and_bound.rs
rust-bitcoin deprecated unchecked ops in commit: https://github.com/rust-bitcoin/rust-bitcoin/pull/3759/commits/b895c9aad4e56ff7cf5420f71ae501f942a81326
Updated benchmark performance using the latest stable compiler and switching to native u64/i64 instead of using unchecked ops results in a nominal performance increase.
> Remove unchecked ops

- src/branch_and_bound.rs
- src/lib.rs
When computing how wasteful a UTXO is, it's possible the waste calculation may return None, making it not possible to consider this UTXO as a candidate for selection.  If there are zero UTXOs that have a waste calculation that is Some, then there are no possible solutions from that pool.
> test: Add check for valid waste

- src/lib.rs
This was added with a Utxo from string implementation which was subsequently removed.
> test: Remove unused struct

- src/branch_and_bound.rs
- src/lib.rs
- src/single_random_draw.rs
Instead of building a random solution using brute force, just seed a solution into the initial pool.  This greatly improves test speed and reduces test complexity.
> test: refactor arb tests

- README.md
- benches/bnb_selection.rs
- benches/srd_selection.rs
- fuzz/fuzz_targets/select_coins.rs
- fuzz/fuzz_targets/select_coins_bnb.rs
- fuzz/fuzz_targets/select_coins_srd.rs
- src/branch_and_bound.rs
- src/lib.rs
- src/single_random_draw.rs
Instead of generic params, use concrete type.
> Use concrete type instead of generic

- src/branch_and_bound.rs
Once the fee-rate's are swapped, the `WeightedUtxo `constructor can return `NONE`, for example if the effective_value is not positive.  This would cause a panic in the test, therefore use `filter_map()` to filter those that return `NONE` and remove `unwrap()`.
> test: remove invalid UTXOs from prop-test result

- src/branch_and_bound.rs
When fee-rate is high, using waste instead of weight creates an optimal sort order leading to an optimal solutions being found in less iterations.
The secondary sort order is used as a tie breaker when effective_values are equivalent.  Therefore, this optimization only is relevant given a pool with equivalent effective_values yet different waste scores.
When fee_rates are high, it's optimal to secondary sort by descending weight, and when fee_rates are low, it's optimal to secondary sort by ascending weight.  However, using a secondary sort by waste, it's always optimal to sort by ascending waste.
Consider the test `select_coins_bnb_effective_value_tie_high_fee_rate`. The optimal solution will be to use `UTXOs` with a lower weight when fee_rate is high.  The previous sort by descending …
> algo: bnb: modify secondary UTXO sort order

- src/branch_and_bound.rs
The test uses an invalid pool that would overflow when the inputs are added together.  Therefore the test could fail due to an overflow in the `UTXO` pool and not when evaluating the upper bound depending on the order of evaluation.  This change creates a valid pool showing that the overflow is due to an invalid upper bound.
> test: improve upper bound test case

- README.md
The previous measurments where using `1.90` unstable (nightly) which is subject to change.
> docs: update benchmark for `1.89` stable

- fuzz/fuzz_targets/select_coins.rs
- fuzz/fuzz_targets/select_coins_bnb.rs
- fuzz/fuzz_targets/select_coins_srd.rs
- fuzz/src/lib.rs
Naming this to `CandidateOutputs` is more closely aligned to what this struct is.  This also keeps the name `UtxoPool` free for use elsewhere without conflict.
> refactor:fuzz: rename struct from UtxoPool to CandidateOutputs

- Cargo.toml
The docs page on docs.rs does not build, and the build logs show it fails due to missing the rand dependence.
> docs: fix build problem on docs.rs
