contrib/test.sh, src/lib.rs
Add rustdoc build to CI script: https://github.com/p2pderivatives/rust-bitcoin-coin-selection/issues/9
=> Add rustdoc build to CI script

Cargo.toml, benches/coin_selection.rs
=> Release preperation

CHANGELOG.md, Cargo.toml, src/branch_and_bound.rs, src/lib.rs
=> Use latest bitcoin version

src/lib.rs
=> Remove trait

Cargo.toml, src/branch_and_bound.rs
=> Refactor bnb tests take two

Cargo.toml, src/branch_and_bound.rs
Update Cargo.toml for publication.  Note to self, run `cargo publish --dry-run` to catch earlier.
=> Reset Cargo file for publication

src/branch_and_bound.rs
No logic change, only a format fix.
=> Fix format

README.md
No logic changes, only updates to the README
=> Group benchmark and performance comparison README sections

src/branch_and_bound.rs
This PR is a collection of spelling fixing and corrections to the documentation.   No change in functionality.
=> Fixup docs

src/branch_and_bound.rs, src/lib.rs, src/single_random_draw.rs
Contains some minor refactors to the test-suit.
=> Refactor branch

src/branch_and_bound.rs, src/lib.rs, src/single_random_draw.rs
This is a number of enhancements and refactors to the test-suit.  More details are added to each commit message.
=> Test enhancements 04 06 2025

src/branch_and_bound.rs
The UTXO skip optimization: 118b1c419391943e0d80d6973fad3c07bd2ed918 introduced a possible in-efficiency such that a solution with a better waste score would be skipped.  If UTXO A is skipped and UTXO B has the same effective_value, then skip UTXO B.  However, it's possible the UTXO B had a better weight (better waste score) than UTXO A therefore it may skip a potentially lower waste solution.  In order to address this, sort the candidate selections using descending effective_value as before, however add a secondary sort of descending satisfaction_weight.  Since the optimization works by comparing the current UTXO to the previous UTXO, the new sort order ensures that the previous UTXO will always have a better waste score than current, therefore if it is skipped, a better solution is not …
=> algo: Add secondary sort by satisfaction_weight

Cargo.toml, README.md, benches/coin_selection.rs, fuzz/Cargo.toml, fuzz/fuzz_targets/select_coins.rs, fuzz/fuzz_targets/select_coins_bnb.rs, fuzz/fuzz_targets/select_coins_srd.rs, src/branch_and_bound.rs, src/lib.rs, src/single_random_draw.rs
The major changes in this PR:
* Monadic Amount/SignedAmount type
* Amount/SignedAmount MAX_MONEY invariant.
=> Upgrade to units 1.0

src/single_random_draw.rs
While summing the total to check if there is enough value to reach the target, return if the sum would overflow or if the sum is not enough to meet the target.  This prevents the random selection routine from being run if there is not enough value to meet the target.
Remove the check that the sum of `UTXO's` does not overflow since this is now being done while summing the available value.
=> refactor: return early if a solution is not possible

src/lib.rs
=> Cleanup outdated todo

src/branch_and_bound.rs, src/lib.rs, src/single_random_draw.rs
Available value is always positive
=> refactor: test: change return type to Amount for available_value()

Cargo.toml, src/branch_and_bound.rs, src/lib.rs
Fix 0.7.0 test module to work against rust-bitcoin 0.32.x
=> 0.7.0 fix tests

README.md, benches/bnb_selection.rs, benches/srd_selection.rs, fuzz/fuzz_targets/select_coins.rs, fuzz/fuzz_targets/select_coins_bnb.rs, fuzz/fuzz_targets/select_coins_srd.rs, src/branch_and_bound.rs, src/lib.rs, src/single_random_draw.rs
=> Add fields to weighted utxo

fuzz/fuzz_targets/select_coins.rs, fuzz/fuzz_targets/select_coins_bnb.rs, fuzz/fuzz_targets/select_coins_srd.rs, fuzz/src/lib.rs
=> refactor:fuzz: consolidate fuzz types

README.md, benches/bnb_selection.rs, benches/srd_selection.rs, fuzz/Cargo.toml, fuzz/fuzz_targets/branch_and_bound.rs, fuzz/fuzz_targets/single_random_draw.rs, src/branch_and_bound.rs, src/lib.rs, src/single_random_draw.rs
The user documentation is more readable using the full name of the algorithm.
=> Rename function calls
